### ISSUE TITLE
Componentes FireDAC

### ISSUE THREAD

**Issue by nfers** [Fluxuss-Development/sistemameumeganegocio#1]
Boa tarde, gostei muito do seu projeto, vi que não separou o código por units, forms, datamodule, e tambem que não usou algumas ferramentas do fireDAC para ajudar na performance e conexao. Posso contribuir com seu projeto?

**Comment by keowu** [comment]
Olá tudo bem ? obrigado pela sua contribuição, no caso das querys e afins todas estão presentes no datamodule sim, porém não foram criadas units em específico para passar parâmetros para execução de instruções sql, quanto a otimização fique a vontade para contribuir eu e minha equipe vamos analisar e aprovar as mudanças, qualquer dúvida e falhas estou a disposição para auxiliar, temos o objetivo de criar uma comunidade sólida para nosso projeto, muito obrigado pelas suas sugestões.
